### ISSUE TITLE
Mod Menu - configuration button is gone.

### ISSUE THREAD

**Issue by Intezium** [The-Fireplace-Minecraft-Mods/Fires-Survival-Tweaks#10]
**Describe the bug**
![2021-03-28_18 20 01](https://user-images.githubusercontent.com/20191322/112757368-45bffe00-8ff2-11eb-93c7-54dd66b998d2.png)

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.16.5
 - Mod Version: 2.1.0
 - Fabric API: 0.32.5

**Comment by The-Fireplace** [comment]
What version of mod menu are you using?

**Comment by Intezium** [comment]
> What version of mod menu are you using?

Mod menu: 1.16.8

**Comment by ImagineRC** [comment]
Did you find a fix? I'm currently trying to disable the cave in aspect and there is no configuration option

**Comment by The-Fireplace** [comment]
In the meantime you can edit the config file directly, it is called `fst.json`

**Comment by The-Fireplace** [comment]
Just so you know, I am looking in to it still. I'm having difficulty reproducing the issue, so fixing it will be difficult. Can you provide a paste of your log file from when this happens?
