### ISSUE TITLE
Crash when hitting y = 0

### ISSUE THREAD

**Issue by snowboundmage2** [The-Fireplace-Minecraft-Mods/Fires-Survival-Tweaks#15]
Quarry mining a chunk made the game crash when it hit y=0, playing with the new official caves prototype

Reproduce:
get the fancy caves
https://feedback.minecraft.net/hc/en-us/articles/4402614709389-Caves-Cliffs-Prototype-Data-Pack-for-Minecraft-Java-Edition
get a quarry or something similar
mine down 9x9 hole
wait til mining y=0

[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/Fires-Survival-Tweaks/files/6871949/latest.log)

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.17.1
 - Mod Version: 2.20
 - Fabric API: 0.37.1

**Comment by The-Fireplace** [comment]
In the future, please use a paste site to paste the logs as requested by the template.
