### ISSUE TITLE
Please... help me... dear god...

### ISSUE THREAD

**Issue by srnyx** [The-Fireplace-Minecraft-Mods/Fires-Survival-Tweaks#7]
**Describe the bug**
All the netherrack on the ceiling is falling and just keeps falling. It won't stop.

**To Reproduce**
1. Install the mod
2. Go to the Nether

**Logs/Screenshots/Videos**
https://imgur.com/a/Oditov0

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.16.5
 - Mod Version: 2.0.0
 - Fabric API: 0.29.4

**Comment by The-Fireplace** [comment]
It's beautiful! I'll see what I can do to help prevent that in the next update. For now, turn off cave-ins.

**Comment by srnyx** [comment]
> It's beautiful! I'll see what I can do to help prevent that in the next update. For now, turn off cave-ins.

It was so satisfying to watch it all fall...

**Comment by The-Fireplace** [comment]
Fixed in 2.1.0
